
INSERT ALL
    INTO SELLS VALUES('Sydney', 'Memantine', 0.54)
    INTO SELLS VALUES('Alaska', 'Doxepin', 0.12)
    INTO SELLS VALUES('South Goa', 'Acetaminophen', 0.75)
    INTO SELLS VALUES('Ranchi', 'Albuterol', 0.82)
    INTO SELLS VALUES('Navi Mumbai', 'Memantine', 0.82)
    INTO SELLS VALUES('Ajmer', 'Doxepin', 0.42)
    INTO SELLS VALUES('New York', 'Liothyrorine', 0.12)
    INTO SELLS VALUES('New York', 'Doxepin', 0.75)
    INTO SELLS VALUES('Navi Mumbai', 'Digoxin', 0.47)
    INTO SELLS VALUES('New York', 'Memantine', 0.42)
    INTO SELLS VALUES('Alaska', 'Memantine', 0.17)
    INTO SELLS VALUES('Chennai', 'Chlomin', 0.47)
    INTO SELLS VALUES('Sydney', 'Doxepin', 0.3)
    INTO SELLS VALUES('Patiala', 'Albuterol', 0.15)
    INTO SELLS VALUES('Alaska', 'Liothyrorine', 0.51)
    INTO SELLS VALUES('Vizag', 'Vasmak', 0.11)
    INTO SELLS VALUES('Sydney', 'Liothyrorine', 0.12)
    INTO SELLS VALUES('Ranchi', 'Penicillin', 0.6)
    INTO SELLS VALUES('Bangalore', 'Prednisone', 0.29)
    INTO SELLS VALUES('Hyderabad', 'Acetaminophen', 0.82)
    INTO SELLS VALUES('Chennai', 'Zolpidem', 0.11)
    INTO SELLS VALUES('Chennai', 'Atolip', 0.58)
    INTO SELLS VALUES('Patiala', 'Chlomin', 0.82)
    INTO SELLS VALUES('Pune', 'Insulin', 0.17)
    INTO SELLS VALUES('Jaipur', 'Lorazepam', 0.12)
    INTO SELLS VALUES('Chandigarh', 'Ibuprofen', 0.15)
    INTO SELLS VALUES('New York', 'Omeprazole', 0.29)
    INTO SELLS VALUES('Bangalore', 'Albuterol', 0.3)
SELECT 1
FROM DUAL;
